# Generated by Django 5.0.1 on 2024-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='last_login_ip',
        ),
        migrations.AddField(
            model_name='influencer',
            name='login_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
