# Generated by Django 5.0.1 on 2024-02-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('influencer', '0002_remove_influencer_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='compaigns',
            field=models.ManyToManyField(blank=True, related_name='influencers', to='campaign.campaign'),
        ),
    ]
