# Generated by Django 5.0.1 on 2024-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('influencer', '0003_influencer_compaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='compaigns',
            field=models.ManyToManyField(blank=True, null=True, related_name='influencers', to='campaign.campaign'),
        ),
    ]
