# Generated by Django 5.0.1 on 2024-02-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_influencer_facebook_influencer_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube',
        ),
    ]
