# Generated by Django 5.0.1 on 2024-02-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(default='null', null=True, upload_to='companies')),
                ('company_name', models.CharField(max_length=230)),
                ('email', models.CharField(max_length=230)),
                ('sector', models.CharField(max_length=230)),
                ('password', models.CharField(max_length=230)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('country', models.CharField(default='Rwanda', max_length=230)),
                ('city', models.CharField(default='Kigali', max_length=230)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=230)),
                ('competitor_image', models.ImageField(default='null', null=True, upload_to='competitors')),
                ('competitor_info', models.CharField(max_length=230)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_image', models.ImageField(default='null', null=True, upload_to='social_media')),
                ('account_link', models.CharField(max_length=230)),
                ('social_media_type', models.CharField(max_length=230)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Social Media Accounts',
            },
        ),
    ]
